### ISSUE TITLE
寻求长期贡献者(核心贡献者)

### ISSUE THREAD

**Issue by sunface** [sunface/rust-by-practice#139]
目前准备按照 Rust语言圣经 那本书的章节来安排相对应的练习题，感兴趣的同学可以一起来做这件事，目前有几个目标：

- 全英文，为所有 Rustacean 开放练习题
- 每个章节的练习题难度满足初 - 中 - 高，循序渐进，目前 rustling、rust-by-example 还是太简单了

总之，这个项目的目标是未来成为全世界 Rust 学习者在语言学习和实践之间的桥梁，目标很宏大，任务也很艰巨，欢迎大家一起参与进来，有意愿的请在下面回复留言～～

**Comment by fireindark707** [comment]
太厉害了！先学会再加入
